Model in Master
Usurpeer/java23-book-store pull request #1
Opened 2024-02-21 23:31 UTC by Usurpeer

Реализовал всё, кроме поиска. Написал ко всему тесты. 

В SearchFilter сделал список книг, а не каталог, тк не понял зачем его таскать. Также в SearchFilter костыли с 
"minPrice != null && maxPrice != null && minPrice.isPresent() && maxPrice.isPresent()" - Почему то exception, когда кладешь null и пытаешься проверить сразу на .isPresent(). Раньше такого вроде не было. Но при этом сама IDE подсказывает, что нужно убрать этот костыль (а без него ломается). 

А в целом, мне кажется можно везде сделать не список книг, а Set. Они же не могут повторяться, нет?

2024-02-25 07:42 UTC, KorobetskayaAA commented
> А в целом, мне кажется можно везде сделать не список книг, а Set. Они же не могут повторяться, нет?

Set - это такая коллекция, где принципиальны следующие свойства: а) отсутствие повторов (и это прямо критически важно); б) редактируемость, можно добавлять и удалять элементы; в) порядок элементов в коллекции не важен.

В целом да, можно сказать, что ваш список книг попадает под критерии (а) и (в). Но я не вижу никаких преимуществ, которые бы давало использование Set. Я бы скорее использовала массив, потому что он нередактируемый и компактный. Но в Java массивы менее удобно использовать со Stream API, чем коллекции, а выгод опять же мало. Поэтому List или даже общий Collection вполне приемлем.

Можно возвращать Set из результатов фильтрации, чтобы подчеркнуть, что в результате своих манипуляций вы никогда не вернете повторов, а порядок сортировки не задан.

2024-02-25 07:46 UTC, KorobetskayaAA requested changes
Нужно исправить применение Optional и создание SearchFilter.

2024-02-25 07:46 UTC, KorobetskayaAA commented on src/main/java/ru/teamscore/java23/books/model/SearchFilter.java
> +@AllArgsConstructor
@AllArgsConstructor - в данном случае простое, но неудобное решение. Фактически, вы заставляете пользователя класса (себя) задавать все параметры фильтрации, хотя на самом деле задан может быть только один. Например, только по макс. цене. А вызвать придется монструозный конструктор вот такого вида:

``` java
SearchFilter(
        Optional<BigDecimal>.empty(), 
        Optional<>.of(BigDecimal.of(500)),
        Optional<Integer>.empty(),
        Optional<Integer>.empty(),
        new Set<Author>(),
        new Set<Genre>.empty(),
        Optional<String>.empty(),
        books
)
```

По сути, обязательный параметр у вас только один - список книг для фильтрации. Вот его надо передать в конструкторе, а потом нужные параметры задать через setter-ы.

Еще можно реализовать паттерн Builder, он есть в Lombok. С ним создание фильтра будет выглядеть как-то так:
```
var filter = SearchFilter.builder()
        .books(books)
        .maxPrice(BigDecimal(500))
        .build();
```

В любом случае, все Optional параметры нужно инициализировать сразу Optional.empty() и убрать final. Для списков авторов и жанров - аналогично.

2024-02-25 07:46 UTC, KorobetskayaAA commented on src/main/java/ru/teamscore/java23/books/model/SearchFilter.java
> +        if (minYear != null && maxYear != null && minYear.isPresent() && maxYear.isPresent()) {
Вам пришлось добавить проверки на null, потому что неправильно используете Optional. Для Optional никогда не используется значение null, для пустого значения используется Optional.empty(). Т.е. пуст объект в Optional, а не он сам.

2024-02-25 07:46 UTC, KorobetskayaAA commented on src/main/java/ru/teamscore/java23/books/model/SearchFilter.java
> +    public List<Book> filterOnPrice(List<Book> books) {
Зачем делать перегрузку с параметром? У вас список книг уже задан в поле. Получается странная смесь параметров и полей. Либо убирайте поле и все методы делайте с передачей List<Book> books, либо убирайте методы с параметром.

2024-02-25 07:46 UTC, KorobetskayaAA commented on src/main/java/ru/teamscore/java23/books/model/SearchFilter.java
> +        if (minPrice == null || maxPrice == null || minPrice.isEmpty() || maxPrice.isEmpty() || books == null) {
Не должен быть Optional null! Инициализируйте правильно Optional.empty(). Везде аналогично.

2024-02-25 07:46 UTC, KorobetskayaAA commented on src/main/java/ru/teamscore/java23/books/model/entities/Book.java
> +    private BigDecimal price; // цена книги
Цена @NonNull

2024-02-25 07:46 UTC, KorobetskayaAA commented on src/main/java/ru/teamscore/java23/books/model/SearchFilter.java
> +                    return bookPrice != null && bookPrice.compareTo(minPrice.get()) >= 0 &&
Проверка цены на null выглядит неестественно. Не должна цена быть null никогда. Добавьте в Book Nonnull для цены.

2024-02-25 07:46 UTC, KorobetskayaAA commented on src/main/java/ru/teamscore/java23/books/model/SearchFilter.java
> +    // Оставлю методы, раз написал
Для истории есть Git. Вы их закоммитили, хорошо. Если не понадобятся, уберите. Если вдруг все-таки понадобятся, всегда можно достать из истории коммитов.

2024-02-25 07:46 UTC, KorobetskayaAA commented on .gitignore
> +.idea/
Вижу, что добавлен .idea/, но содержимое папки .idea все равно закоммитилось. Надо сначала закоммитить .gitignore, чтобы он применился. Можно ручную исключить из коммита лишние файлы, пока в него не попал .gitignore.

2024-02-26 20:24 UTC, Usurpeer commented
Запушил исправления данной ветки. Пришлось использовать конструкцию @NonNull + @Builder.Default в SearchFilter, чтобы нельзя было передать null значение и всё сломать. Не знаю правильно ли так.
После такого всё еще необходимо использование Optional?

Еще убрал final у всех полей, может я что-то не так понял из вашего замечания.

Ну и тесты все проверил исправил.

Удалил idea из гита.

2024-02-28 05:51 UTC, KorobetskayaAA approved these changes

2024-02-28 05:51 UTC, merged